### ISSUE TITLE
How does Dino based on ViT14 support 1024 inputs?

### ISSUE THREAD

**Issue by zhaoyuan1209** [caoyunkang/VarAD#2]
It seems that deno based on ViT14 only supports image sizes that are integer multiples of 14. How did you make it support 1024 inputs?

**Comment by caoyunkang** [comment]
Sorry for the misunderstanding.. We round down the actual resolution to the nearest multiple of 14 to make ViT14 work, for example 1024 will be 1022.

**Comment by zhaoyuan1209** [comment]
Thank you for your patient reply!
